name: Workflow Manual

on: 
    workflow_dispatch:
env:
  BRANCH_NAME: ${{ github.ref_name }} 
  VERSION: ${GITHUB_REF##*/}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Show environment v1
              run: env | grep ^GITHUB
            - name: Show ref v1
              run: echo "===============> Version from $GITHUB_REF"
            - name: Show ref v2
              run: echo "===============> Version from ${{ env.VERSION }}"