name: After Create Branch Release
on:
  push:
    branches:
      - release/*
permissions:
  pull-requests: write
  contents: write
jobs:
  after-release:
    runs-on: ubuntu-latest
    steps:
        - name: Show parametros
          run: echo "===============> Version from ${GITHUB_REF##*/}"
  release-tag:
    needs: after-release #dependencia
    name: Releases and Tags
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
        - name: Prepare Release Body
          uses: cschleiden/replace-tokens@v1
          with:
            files: '["${{ github.workspace }}/.github/docs/release_body.md"]'
          env:
            RELEASE_TAG_LATEST_VERSION: ${GITHUB_REF##*/}
            RELEASE_TAG_CHANGES: 'Texto changelog'
            ACTOR: 'Nome do autor'
        - name: Create GitHub Release
          uses: ncipollo/release-action@v1
          id: release
          with:
            updateOnlyUnreleased: true
            bodyFile: ".github/docs/release_body.md"
            commit: "main"
            tag: '${GITHUB_REF##*/}'
            makeLatest: "latest"
