name: After Create Branch Release
on:
  push:
    branches:
      - release/*
permissions:
  pull-requests: write
  contents: write
jobs:
  after-release:
    runs-on: ubuntu-latest
    steps:
        - name: Show parametros
          run: echo "===============> Version from ${GITHUB_REF##*/}"
  release-tag:
    needs: after-release #dependencia
    name: Releases and Tags
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
        - name: Create GitHub Release
          uses: ncipollo/release-action@v1
          with:
            updateOnlyUnreleased: true
            body: "Version from ${{ github.ref }}"
            tag: "1.0.0"
            makeLatest: "latest"
