name: After Create Branch Release
on:
  push:
    branches:
      - release/*

permissions:
  pull-requests: write
  contents: write
env:
  BRANCH_NAME: ${{ github.ref_name }} 
  VERSION: ""
jobs:
  after-release:
    runs-on: ubuntu-latest
    steps:
        - name: Show parametros
          run: echo "===============> Version from ${GITHUB_REF##*/}"
  release-tag:
    needs: after-release #dependencia
    name: Releases and Tags
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
        - name: Get Version
          id: get_version
          run: EXPORT $VERSION="${GITHUB_REF##*/}"
          #run:  echo "::set-output name=version::${GITHUB_REF##*/}"
        - name: Create GitHub Release
          uses: ncipollo/release-action@v1
          with:
            updateOnlyUnreleased: true
            body: "Version from ${{ github.ref }}"
            tag: ${{ env.VERSION }}
            commit: ${{ env.BRANCH_NAME }}
            makeLatest: "latest"
  final:
    needs: release-tag
    runs-on: ubuntu-latest
    steps:
        - name: Teste final
          run: echo "===============> Teste ${{ env.VERSION }}"
