name: After Release
on: 
    workflow_dispatch:
permissions:
  pull-requests: write
  contents: write
env:
  BRANCH_NAME: ${{ github.ref_name }} 
jobs:
  after-release:
    runs-on: ubuntu-latest
    steps:
        - name: Show parametros
          run: echo "===============> Version from ${GITHUB_REF##*/}"
  release-tag:
    needs: after-release #dependencia
    name: Releases and Tags
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
        - name: Get Version
          id: get_version
          run:  echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
        - name: Create GitHub Release
          run: echo "===============> Version from ${{ env.VERSION }}"
  final:
    needs: release-tag
    runs-on: ubuntu-latest
    steps:
        - name: Teste final
          run: echo "===============> Teste ${{ env.VERSION }}"
