name: After Release
on: 
    workflow_dispatch:
permissions:
  pull-requests: write
  contents: write
env:
  BRANCH_NAME: ${{ github.ref_name }} 
jobs:
  after-release:
    runs-on: ubuntu-latest
    steps:
        - name: Show parametros
          run: echo "===============> Version from ${GITHUB_REF##*/}"
  release-tag:
    needs: after-release #dependencia
    name: Releases and Tags
    runs-on: ubuntu-latest
    outputs:
        version: ${{ steps.get_version.outputs.version }}
    defaults:
      run:
        shell: bash
    steps:
        - name: Get Version
          id: get_version
          run:  echo "version=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        - name: Create GitHub Release
          run: echo "===============> Version from ${{ steps.get_version.outputs.version }}"
  final:
    needs: release-tag
    runs-on: ubuntu-latest
    steps:
        - name: Teste final
          run: echo "===============> Teste ${{ needs.release-tag.outputs.version }}"
