name: After Release

on:
  release:
    types: [published]

jobs:
  after-release:
    runs-on: ubuntu-latest
    steps:
        - name: Show parametros
          run: echo "nome: ${{ github.event.release.name }} - descricao: ${{ github.event.release.body }} - tag: ${{ github.event.release.tag_name }}"